"use client";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
import Navbar from "./component/Navbar";
import Product from "./component/Product";

export default function Home() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const response = await axios.get("./api/product");
        setProducts(response.data);
      } catch (error) {
        console.error("Error fetching products:", error);
      }
    };

    fetchProducts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="container mx-auto mt-8 px-4 md:px-0">
        <h1 className="text-4xl font-bold text-center text-gray-800">
          Our Products
        </h1>
        <p className="text-center text-gray-600 mt-2">
          Explore our wide range of products. Quality and satisfaction
          guaranteed.
        </p>
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
          {products.map((product) => (
            <Product key={product.id} product={product} />
          ))}
        </div>
      </section>
    </div>
  );
}
